Aip 7108 graph ql survey create functionaliteiten unittests
Amsterdam/bmi-aip-graphql-service pull request #113
Opened 2022-09-19 09:09 UTC by anaim

2022-09-19 10:51 UTC, svbeusekom approved these changes
Looks good, but tests are failing

2022-09-19 13:35 UTC, fortunato commented on src/schema/survey/survey.factory.spec.ts
> +	test('CreateElementInput', () => {
Can you fix the test name/description?

2022-09-19 13:53 UTC, anaim commented on src/schema/survey/survey.resolver.spec.ts
> +describe('Decomposition / Element / Resolver', () => {
PR is updated! changes in van gekopieerd files waren niet opgeslagen!!

2022-09-19 13:54 UTC, anaim commented on src/schema/survey/survey.factory.spec.ts
> +	test('CreateElementInput', () => {
PR is updated! changes in van gekopieerd files waren niet opgeslagen!!

2022-09-19 14:12 UTC, fortunato requested changes

2022-09-19 14:12 UTC, fortunato commented on src/schema/survey/survey.repository.spec.ts
> +				inspectionStandardType: '__INSPECTIONSTANDARDTYPE__',
I think we should copy the `InspectionStandardTypes` enum from AIP for this

2022-09-19 14:12 UTC, fortunato commented on src/schema/survey/survey.repository.spec.ts
> +			inspectionStandardType: '__INSPECTIONSTANDARDTYPE__',
Can we make this an enum value?

2022-09-19 14:12 UTC, fortunato commented on src/schema/survey/survey.resolver.spec.ts
> +//const surveyRepo = new SurveyRepository(prismaServiceMock);
Can this be removed?

2022-09-19 14:12 UTC, fortunato commented on src/schema/survey/__stubs__/survey.ts
> +survey1.inspectionStandardType = '__INSPECTIONSTANDARDTYPE__';
Can we use an enum for this for correctness?

2022-09-19 14:12 UTC, fortunato commented on src/schema/survey/__stubs__/survey.ts
> +	inspectionStandardType: '__INSPECTIONSTANDARDTYPE__',
Can we use an enum for this for correctness?

2022-09-19 14:12 UTC, fortunato commented on src/schema/survey/__stubs__/survey.ts
> +	inspectionStandardType: '__INSPECTIONSTANDARDTYPE__',
Can we use an enum for this for correctness?

2022-09-19 14:12 UTC, fortunato commented on src/schema/survey/survey.factory.spec.ts
> +			inspectionStandardType: '__INSPECTIONSTANDARDTYPE__',
Can we use an enum for this for correctness?

2022-09-19 14:55 UTC, anaim commented on src/schema/survey/__stubs__/survey.ts
> +	inspectionStandardType: '__INSPECTIONSTANDARDTYPE__',
Done

2022-09-19 14:55 UTC, anaim commented on src/schema/survey/__stubs__/survey.ts
> +survey1.inspectionStandardType = '__INSPECTIONSTANDARDTYPE__';
Done

2022-09-19 14:55 UTC, anaim commented on src/schema/survey/survey.resolver.spec.ts
> +//const surveyRepo = new SurveyRepository(prismaServiceMock);
Done

2022-09-19 14:55 UTC, anaim commented on src/schema/survey/survey.repository.spec.ts
> +			inspectionStandardType: '__INSPECTIONSTANDARDTYPE__',
Done

2022-09-19 14:55 UTC, anaim commented on src/schema/survey/survey.repository.spec.ts
> +				inspectionStandardType: '__INSPECTIONSTANDARDTYPE__',
Done

2022-09-19 14:55 UTC, anaim commented on src/schema/survey/__stubs__/survey.ts
> +	inspectionStandardType: '__INSPECTIONSTANDARDTYPE__',
Done

2022-09-19 14:55 UTC, anaim commented on src/schema/survey/survey.factory.spec.ts
> +			inspectionStandardType: '__INSPECTIONSTANDARDTYPE__',
Done

2022-09-21 11:29 UTC, fortunato approved these changes

2022-09-27 09:35 UTC, merged