feat(ark-reach-segments): added scaffolding, tests, and types for rea…
Amsterdam/bmi-aip-graphql-service pull request #202
Opened 2022-12-28 14:19 UTC by bennyvdhoogen

…ch-segments based on support systems

2022-12-28 14:41 UTC, bennyvdhoogen commented
Is related to the following Merge Request in the `aip` repo: https://git.data.amsterdam.nl/bmi/aip/-/merge_requests/1520

2022-12-28 15:58 UTC, anaim commented on src/schema/ark-survey/models/ark-reach-segment.model.ts
> +// import { Point } from 'graphql-geojson-scalar-types';
Kan je dit verwijderen?

2022-12-28 15:58 UTC, anaim commented on src/schema/ark-survey/ark-reach-segment.repository.ts
> +	// 	const result = await this.prisma.$queryRaw<{ geography?: Point | null }>`
Kan je dit verwijderen?

2022-12-28 15:58 UTC, anaim commented on src/schema/ark-survey/ark-reach-segment.repository.ts
> +		console.log(reachSegments);
Kan je dit verwijderen?

2022-12-30 17:02 UTC, fortunato requested changes
Nice work senor. 
I commented on a couple of minor things.
Aside form that, may I suggest we remove the `ark-` prefix from the filenames? We chose not to do that for the span-installation entities either. The top level directory could be named "reach-segments" to better align with the other naming below `schema/` I'd argue.
I am noticing that we probably haven't filled you in on the CASL/role guard situation yet, let's do that next week.

2023-01-02 10:02 UTC, bennyvdhoogen commented on src/schema/ark-survey/__stubs__/ark-survey-stub.ts
> +domainSurvey.inspectionStandardType = 'quaywalls';
Will change this to use the InspectionStandard enum. Also happy to rename it, but not really sure if that's a common convention. Looking at this thread (*https://stackoverflow.com/questions/1335959/singular-or-plural-for-enumerations) there's not really a definitive convention, but there's some guidelines that Microsoft provides for .NET development that suggest to use singular for these cases.

In the codebase I can find both. (eg: `Action` opposed to `Actions`, `SupportSystemType` opposed to `SupportSystemTypes`).

2023-01-02 10:07 UTC, bennyvdhoogen commented on src/schema/ark-survey/__stubs__/ark-survey-stub.ts
> +domainSurvey.inspectionStandardType = 'quaywalls';
Agree on the removal of `ark-` prefix btw, will rename the top level directory to `reach-segments` and rename files accordingly. I'll make sure to remove any prefixes for variable/method names along the way as well. 

(I have some questions regarding this with relation to the to be developed geography data entity/record but will keep that out of this thread)

2023-01-02 10:35 UTC, fortunato commented on src/schema/ark-survey/__stubs__/ark-survey-stub.ts
> +domainSurvey.inspectionStandardType = 'quaywalls';
> Will change this to use the InspectionStandard enum. Also happy to rename it, but not really sure if that's a common convention. Looking at this thread (*https://stackoverflow.com/questions/1335959/singular-or-plural-for-enumerations) there's not really a definitive convention, but there's some guidelines that Microsoft provides for .NET development that suggest to use singular for these cases.
> 
> In the codebase I can find both. (eg: `Action` opposed to `Actions`, `SupportSystemType` opposed to `SupportSystemTypes` both more recently the reverse: `SurveyStates` opposed to `SurveyState` and `CyclicMeasureType` instead of `CylicMeasureTypes`).

Thanks for looking into that :pray: I guess we should make a decision either way. Do you want to through a suggestion/poll up on #coding-standards or #aip_devs?

2023-01-03 16:20 UTC, bennyvdhoogen commented on src/schema/ark-survey/ark-reach-segment.repository.spec.ts
> +		const reachSegment = prismaServiceMock.arkSurveyReachSegments.create.mock.calls[0][0].data as ReachSegment;
Fixed!

2023-01-03 16:20 UTC, bennyvdhoogen commented on src/schema/ark-survey/ark-reach-segment.repository.ts
> +		const reachSegment = await this.prisma.arkSurveyReachSegments.create({ data });
Fixed!

2023-01-03 16:20 UTC, bennyvdhoogen commented on src/schema/ark-survey/ark-reach-segment.repository.ts
> +		})) as ReachSegment[];
Fixed!

2023-01-03 16:20 UTC, bennyvdhoogen commented on src/schema/ark-survey/ark-reach-segment.repository.ts
> +		return Promise.all(
Fixed!

2023-01-03 16:20 UTC, bennyvdhoogen commented on src/schema/ark-survey/ark-reach-segment.repository.ts
> +		const reachSegment = await this.prisma.arkSurveyReachSegments.update({
Fixed!

2023-01-03 16:20 UTC, bennyvdhoogen commented on src/schema/ark-survey/ark-reach-segment.repository.ts
> +		const reachSegment = await this.prisma.arkSurveyReachSegments.update({
Fixed!

2023-01-03 16:27 UTC, bennyvdhoogen commented on src/schema/ark-survey/__stubs__/ark-survey-stub.ts
> +domainSurvey.inspectionStandardType = 'quaywalls';
Yes, I've created the poll. Looks like we're leaning towards singular form at the moment. 

I've removed the test that touches this enum however, as I felt that during the removal of the ARK prefix/namespace this /reach-segments/ became more of a specific unit of functionality decoupled from the Ark inspection type. It felt out of place to have a test that touches the createSurvey logic in the folder.

2023-01-04 06:34 UTC, fortunato reviewed
LGTM. I'm just wondering if it's worth renaming a few methods in line with the convention we discussed last week about find* vs get* where find is used when a multiple could be returned and get if a single record/value is returned. Would you agree that that applies here as well?

2023-01-04 06:34 UTC, fortunato commented on src/schema/reach-segment/reach-segment.repository.ts
> +	async getReachSegments(surveyId: string): Promise<ReachSegment[]> {
From our discussion the other day about find vs get in a GQL query context I'd expect this to be named `findReachSegments` and the method above `getHighestSortNumber`. Do you agree that concept applies here as well?

2023-01-04 09:41 UTC, bennyvdhoogen commented on src/schema/reach-segment/reach-segment.repository.ts
> +	async getReachSegments(surveyId: string): Promise<ReachSegment[]> {
Yes, for sure. I'll change it!

I'd like to add however, that I've based this naming on support-systems. Doing this now while also having similar methods in the codebase for other entities that don't adhere to this convention can cause confusion. Do you think we should refactor this for other entities?

2023-01-04 12:11 UTC, fortunato commented on src/schema/reach-segment/reach-segment.repository.ts
> +	async getReachSegments(surveyId: string): Promise<ReachSegment[]> {
I think we should. Maybe we can add a ticket to the backlog in line with AIP-9751?

2023-01-04 12:11 UTC, fortunato approved these changes

2023-01-04 13:57 UTC, merged

2023-01-04 14:11 UTC, bennyvdhoogen commented on src/schema/reach-segment/reach-segment.repository.ts
> +	async getReachSegments(surveyId: string): Promise<ReachSegment[]> {
Done -> https://datapunt.atlassian.net/browse/AIP-9766