Feature/aip 7419 ark survey results
Amsterdam/bmi-aip-graphql-service pull request #219
Opened 2023-01-12 08:11 UTC by bennyvdhoogen

2023-01-12 09:14 UTC, bennyvdhoogen commented
Depending on the migrations in this MR: https://git.data.amsterdam.nl/bmi/aip/-/merge_requests/1520

2023-01-12 14:25 UTC, fortunato requested changes
Neat! Few minor thingies

2023-01-12 14:25 UTC, fortunato commented on src/schema/ark-survey/__stubs__/geography-data-stub.ts
> +//updateArkSurvey.id = '1f728e79-1b89-4333-a309-ea93bf17667c';
Can this be removed?

2023-01-12 14:25 UTC, fortunato commented on src/schema/ark-survey/__stubs__/geography-data-stub.ts
> +//saveArkSurveyInput.id = '1f728e79-1b89-4333-a309-ea93bf17667c';
Can this be removed?

2023-01-12 14:25 UTC, fortunato commented on src/schema/ark-survey/__stubs__/geography-data-stub.ts
> +	ArkGeographyStart: {
As discussed on slack. Let's drop the `Ark` prefix and in the future drop the capitalization and stick to camelcase.

2023-01-12 14:25 UTC, fortunato commented on src/schema/ark-survey/ark-survey.resolver.ts
> +	@Roles({ roles: ['realm:aip_owner', 'realm:aip_admin', 'realm:aip_survey'], mode: RoleMatchingMode.ANY })
Are surveyors allowed to delete a survey?

2023-01-13 11:14 UTC, bennyvdhoogen commented on src/schema/ark-survey/__stubs__/geography-data-stub.ts
> +	ArkGeographyStart: {
Yes, will do. Also renaming the columns in the db via a migration in the AIP repository.

2023-01-13 11:16 UTC, bennyvdhoogen commented on src/schema/ark-survey/ark-survey.resolver.ts
> +	@Roles({ roles: ['realm:aip_owner', 'realm:aip_admin', 'realm:aip_survey'], mode: RoleMatchingMode.ANY })
Ah, I suppose `realm:aip_survey` means ANY surveyor. Must be just the owner. I'll remove `realm:aip_survey`.

2023-01-16 09:19 UTC, anaim approved these changes

2023-01-16 14:34 UTC, merged