Feature/baip 468
Amsterdam/bmi-aip-graphql-service pull request #236
Opened 2023-01-24 21:27 UTC by anaim

2023-01-30 09:45 UTC, fortunato requested changes
I am not seeing any `@ResolveField` decorators yet for fetching the entities related to measures and cyclic measures. Will you be adding these now that we have a the models set up?

2023-01-30 09:45 UTC, fortunato commented on src/schema/failure-mode/failure-mode.factory.spec.ts
> +		// const object = {
Can this be removed?

2023-01-30 09:45 UTC, fortunato commented on src/schema/failure-mode/failure-mode.repository.ts
> +			// copyOfFailureModeId,
What's up with these?

2023-01-30 09:45 UTC, fortunato commented on src/schema/failure-mode/failure-mode.resolver.spec.ts
> +		test('updates and returns an failureMode', async () => {
Typo, should be: "returns a failureMode"

2023-01-30 09:45 UTC, fortunato commented on src/schema/failure-mode/types/failure-mode.repository.interface.ts
> +	// findFailureModes(surveyId: string): Promise<FailureMode[]>;
Can this be removed?

2023-01-30 09:45 UTC, fortunato commented on src/schema/ti/condition.factory.ts
> +// import { CreateConditionInput } from './dto/create-condition.input';
Can this be removed?

2023-01-30 09:45 UTC, fortunato commented on src/schema/ti/models/defect.model.ts
> +	// TODO Ensure the Condition model can be retrieved as a property
I think this should be addressed. Can I ask you to make this happen?

2023-02-01 09:51 UTC, bennyvdhoogen commented on src/schema/failure-mode/models/failure-mode-meta-data.model.ts
> +	public bronVanValen?: string;
Typo here: 'bronVanValen' should be 'bronVanFalen' I suppose. See this in other places as well, but I suppose those are just refering to this one.

2023-02-01 10:29 UTC, bennyvdhoogen commented on src/schema/failure-mode/models/failure-mode.model.spec.ts
> +		// failureMode.function = null;
Can be removed?

2023-02-01 10:29 UTC, bennyvdhoogen commented on src/schema/failure-mode/models/failure-mode.model.spec.ts
> +		// failureMode.failureMode = null;
Can be removed?

2023-02-01 10:29 UTC, bennyvdhoogen commented on src/schema/failure-mode/models/failure-mode.model.spec.ts
> +			// function: null,
Can be removed?

2023-02-01 10:29 UTC, bennyvdhoogen commented on src/schema/failure-mode/models/failure-mode.model.spec.ts
> +			// failureMode: null,
Can be removed?

2023-02-01 10:40 UTC, bennyvdhoogen commented on src/schema/survey/survey.repository.ts
> +	async createSurvey(input: CreateSurveyInput): Promise<DbSurvey> {
Why this name change tot DbSurvey? I understand the distinction you want to make between the Model Survey and the raw database output from the `surveys` table within this repository, but shouldn't the repository make sure that the output is the model Survey?

2023-02-01 10:42 UTC, bennyvdhoogen commented on src/schema/ti/condition.resolver.spec.ts
> +	// });
Can you remove this if it is unused?

2023-02-01 10:44 UTC, bennyvdhoogen reviewed
Looks good! Few minor remarks.

2023-02-02 09:34 UTC, bennyvdhoogen approved these changes

2023-02-02 09:38 UTC, merged