feat:generate cyclicMeasures
Amsterdam/bmi-aip-graphql-service pull request #279
Opened 2023-02-16 10:37 UTC by anaim

2023-02-20 16:16 UTC, bennyvdhoogen approved these changes

2023-02-21 08:34 UTC, fortunato requested changes

2023-02-21 08:34 UTC, fortunato commented on src/schema/measure/cyclic-measure.repository.ts
> +				const unitCode: ObjectTypeUnitCode = await this.prisma.objectTypeUnitCodes.findFirst({
I think ideally we don't mix concerns from different domains. This is a repository responsible for cyclicMeasures, not objectTypeUnitCodes.
I think this method/logic would be better situated in the command handler. The command handler can then have the necessary services and repositories (a kind of service really) injected to get the job done. This way we are not mixing concerns related to different domains/entities on the service/repository level.

2023-02-21 08:34 UTC, fortunato commented on src/schema/measure/utils/cast-cyclic-measure-type.ts
> +export const castCyclicMeasureType = (maintenanceType: string) => {
Neat. Is it worth making it explicit that the return type is an enum or a string?

2023-02-27 07:31 UTC, anaim commented on src/schema/measure/cyclic-measure.repository.ts
> +				const unitCode: ObjectTypeUnitCode = await this.prisma.objectTypeUnitCodes.findFirst({
Done

2023-02-27 07:31 UTC, anaim commented on src/schema/measure/utils/cast-cyclic-measure-type.ts
> +export const castCyclicMeasureType = (maintenanceType: string) => {
Done

2023-02-27 08:47 UTC, fortunato requested changes

2023-02-27 08:47 UTC, fortunato commented on src/schema/measure/dto/create-cyclic-measure.input.ts
> +	// @Field()
Can this be removed?

2023-02-27 08:47 UTC, fortunato commented on src/schema/measure/commands/generate-cyclic-measures.handler.ts
> +								(await this.cyclicMeasureRepository.createCyclicMeasure(
Can we use a factory to transform a Prisma result to a CyclicMeasure GQL model?

2023-02-27 08:47 UTC, fortunato commented on src/schema/measure/commands/generate-cyclic-measures.handler.ts
> +								(await this.cyclicMeasureRepository.updateCyclicMeasure(
Can we use a factory to transform a Prisma result to a CyclicMeasure GQL model?

2023-02-27 09:12 UTC, fortunato approved these changes

2023-02-27 14:48 UTC, anaim commented on src/schema/measure/commands/generate-cyclic-measures.handler.ts
> +								(await this.cyclicMeasureRepository.createCyclicMeasure(
Done

2023-02-27 14:48 UTC, anaim commented on src/schema/measure/commands/generate-cyclic-measures.handler.ts
> +								(await this.cyclicMeasureRepository.updateCyclicMeasure(
Done

2023-02-28 10:23 UTC, merged