Feature/BAIP-464-optional-fields-measure-input
Amsterdam/bmi-aip-graphql-service pull request #289
Opened 2023-02-27 15:05 UTC by bennyvdhoogen

2023-02-27 17:38 UTC, fortunato requested changes

2023-02-27 17:38 UTC, fortunato commented on src/schema/measure/measure.factory.ts
> +		measure.surveyScopeId = surveyScopeId ?? null;
Doesn't Prisma already return null for these?

2023-02-27 17:38 UTC, fortunato commented on src/schema/measure/measure.repository.ts
> +		if (remarks) {
Could've done without the condition here. I believe Prisma either returns null or a string.

2023-02-27 17:38 UTC, fortunato commented on src/schema/measure/measure.repository.ts
> +		if (remarks) {
Could've done without the condition here. I believe Prisma either returns null or a string.

2023-02-27 17:57 UTC, bennyvdhoogen commented on src/schema/measure/measure.repository.ts
> +		if (remarks) {
I believe by default it does indeed return an empty string, which does not play nice with the isUUID decorator. There probably is a more concise way to do this, but I wouldn't know how.

2023-02-28 14:27 UTC, bennyvdhoogen commented
> I believe by default it does indeed return an empty string, which does not play nice with the isUUID decorator. There probably is a more concise way to do this, but I wouldn't know how. 

Nope, this is nonsense. You were right.

2023-02-28 14:28 UTC, bennyvdhoogen commented on src/schema/measure/measure.repository.ts
> +		if (remarks) {
Nope, this is nonsense. You were right.

2023-02-28 14:31 UTC, anaim approved these changes

2023-02-28 14:53 UTC, merged