Feature/baip 1159
Amsterdam/bmi-aip-graphql-service pull request #303
Opened 2023-03-07 13:11 UTC by mumuchuchu

No test yet!

2023-03-08 16:56 UTC, bennyvdhoogen commented on src/command/cli/nen2767-migrate-decomposition.cli.ts
> +		const queue = new PQueue({ concurrency: 5 });
Why do you need to change the concurrency here?

2023-03-08 16:56 UTC, bennyvdhoogen commented
I took the liberty to change the base branch to acceptance

2023-03-08 16:59 UTC, bennyvdhoogen commented on src/schema/facade-follow-up-survey/facade-follow-up-survey.repository.ts
> +			return this.createFacadeFollowUpSurvey(insertData);
Comment can be removed

2023-03-08 17:00 UTC, bennyvdhoogen commented on src/schema/facade-follow-up-survey/facade-follow-up-survey.repository.ts
> +			return this.createFacadeFollowUpSurvey(insertData);
I think I did this (the commented out code) previously to make sure that the GraphQL response matches the actually saved data. I recall seeing the initial saved state as a response if I didn't execute this update part.

2023-03-08 17:03 UTC, bennyvdhoogen commented on src/schema/survey/survey.service.ts
> +	}
Very nicely placed in the general SurveyService!

I do feel that line 39 can be simplified though. Isn't `survey.inspectionStandardData` castable to JSON already?

2023-03-14 16:43 UTC, fortunato requested changes
Nice work Muchu. It's looking solid to me mostly.

2023-03-14 16:43 UTC, fortunato commented on src/schema/facade-follow-up-survey/facade-follow-up-survey.repository.ts
> +		})) as DbSurvey;
This shouldn't require a type cast.

2023-03-14 16:43 UTC, fortunato commented on src/schema/facade-follow-up-survey/dto/inspection-standard-data.input.ts
> +import { Field, InputType } from '@nestjs/graphql';
I like it :ok_hand:

2023-03-14 16:43 UTC, fortunato commented on src/schema/facade-follow-up-survey/dto/update-facade-follow-up-survey.input.ts
> +// import { IsOptional } from 'class-validator';
Can be removed

2023-03-14 16:43 UTC, fortunato commented on src/schema/facade-follow-up-survey/facade-follow-up-survey.repository.spec.ts
> +		repository = new FacadeFollowUpSurveyRepository(prismaServiceMock);
I would classify this as useless assignment.
Why not just do `const returnValue = await new FacadeFollowUpSurveyRepository(prismaServiceMock).updateFacadeFollowUpSurvey(...` in the test?

2023-03-14 16:43 UTC, fortunato commented on src/schema/facade-follow-up-survey/facade-follow-up-survey.repository.ts
> +		})) as DbSurvey;
You can simplify it to this:
```typescript
		// Find existing record in survey table
		const existingRecord = await this.prisma.surveys.findFirst({
			where: { id: surveyId },
		});

		if (!existingRecord) throw new Error('No survey found.');

		// Update data in survey table
		return this.prisma.surveys.update({
			where: {
				id: surveyId,
			},
			data: {
				preparedAuthor: preparedAuthor ?? existingRecord.preparedAuthor,
				preparedDate: preparedDate ?? existingRecord.preparedDate,
				verifiedAuthor: verifiedAuthor ?? existingRecord.verifiedAuthor,
				verifiedDate: verifiedDate ?? existingRecord.verifiedDate,
				inspectionStandardData:
					(inspectionStandardData as Prisma.InputJsonObject) ?? existingRecord.inspectionStandardData,
			},
		});
```

2023-03-14 16:43 UTC, fortunato commented on src/schema/facade-follow-up-survey/facade-follow-up-survey.resolver.ts
> +		const domainFacadeFollowUpSurvey: DomainFacadeFollowUpSurvey =
There's no need to explicitly type this here. TS is perfectly able to infer the type.
Also it could be shortened to:
```typescript
@Mutation(() => FacadeFollowUpSurvey)
@Roles({ roles: ['realm:aip_owner', 'realm:aip_admin', 'realm:aip_survey'], mode: RoleMatchingMode.ANY })
public async updateFacadeFollowUpSurvey(
	@Args('updateFacadeFollowUpSurvey') input: UpdateFacadeFollowUpSurveyInput,
): Promise<FacadeFollowUpSurvey> {
	return FacadeFollowUpSurveyFactory.createFacadeFollowUpSurvey(
		await this.commandBus.execute<UpdateFacadeFollowUpSurveyCommand>(
			new UpdateFacadeFollowUpSurveyCommand(input),
		),
	);
}

```

2023-03-14 16:43 UTC, fortunato commented on src/schema/facade-follow-up-survey/facade-follow-up-survey.resolver.ts
> +	@ResolveField()
Why would you create these as field resolvers rather than just include them in the `getFacadeFollowUpSurvey` query?

2023-03-15 20:47 UTC, mumuchuchu commented on src/schema/facade-follow-up-survey/facade-follow-up-survey.resolver.ts
> +	@ResolveField()
True, I don't need both

2023-03-15 20:50 UTC, mumuchuchu commented on src/schema/survey/queries/find-prepared-date-by-id.handler.ts
> +import { QueryHandler, IQueryHandler } from '@nestjs/cqrs';
I actually don't need this now for this entity but I will make a generic one for Ark.

2023-03-15 20:50 UTC, mumuchuchu commented on src/schema/survey/queries/find-verified-date-by-id.handler.ts
> +import { QueryHandler, IQueryHandler } from '@nestjs/cqrs';
I actually don't need this now for this entity but I will make a generic one for Ark

2023-03-15 20:50 UTC, mumuchuchu commented on src/schema/survey/queries/find-verified-author-by-id.handler.ts
> +import { QueryHandler, IQueryHandler } from '@nestjs/cqrs';
I actually don't need this now for this entity but I will make a generic one for Ark

2023-03-20 09:41 UTC, fortunato approved these changes

2023-03-20 09:58 UTC, merged