Feature/baip 1569 add permanentId to span decomposition
Amsterdam/bmi-aip-graphql-service pull request #387
Opened 2023-05-15 11:50 UTC by mumuchuchu

2023-05-15 12:35 UTC, fortunato requested changes

2023-05-15 12:35 UTC, fortunato commented on src/schema/span-installation/junction-box.repository.ts
> +						permanentId: ovsSurveyId,
I think the value should be the junctionBox.id and not the surveyId, the surveyId is already stored on this record.
If we use the id of the original junctionBox we can connect all potential clones of the original junctionBox and also work out what survey each belongs to (original or cloned).

2023-05-15 12:35 UTC, fortunato commented on src/schema/span-installation/models/junction-box.model.ts
> +	// For contract 3 (spanMeasures) survey: This is a reference for the surveyId that the decompositions are coloned from.
Not the survey Id but the id of the junctionBox in contract 1

2023-05-15 12:58 UTC, mumuchuchu commented on src/schema/span-installation/junction-box.repository.ts
> +						permanentId: ovsSurveyId,
Ok

2023-05-15 12:58 UTC, mumuchuchu commented on src/schema/span-installation/models/junction-box.model.ts
> +	// For contract 3 (spanMeasures) survey: This is a reference for the surveyId that the decompositions are coloned from.
Ok

2023-05-16 08:20 UTC, fortunato approved these changes

2023-05-16 09:03 UTC, merged