Feature/baip 1476 xlsx import for options list
Amsterdam/bmi-aip-graphql-service pull request #395
Opened 2023-05-17 13:59 UTC by bennyvdhoogen

2023-05-19 08:21 UTC, fortunato requested changes
Looks neat :+1: 

A couple of minor remarks.

2023-05-19 08:21 UTC, fortunato commented on src/services/import-span-measure-options.ts
> +		const formattedData = data.map((row) => {
Useless assignment

2023-05-19 08:21 UTC, fortunato commented on src/services/import-span-measure-options.ts
> +		const fetchMaterialen = this.fetchMaterialenFromSheet(file['M-nummers'], this.jsonData.spanMeasureItemOptions);
To me `fetch*` implies an async method that retrieves something using a request.

2023-05-19 08:21 UTC, fortunato commented on src/services/import-span-measure-options.ts
> +		const material = {
Useless assignment

2023-05-19 08:21 UTC, fortunato commented on src/services/import-span-measure-options.ts
> +		const specificationItem = {
Useless assignment

2023-05-19 08:21 UTC, fortunato commented on src/services/import-span-measure-options.ts
> +		const array = key.toString().split(',');
What do you think about chaining this bit too and do with one less assignment?

2023-05-19 08:21 UTC, fortunato commented on src/services/import-span-measure-options.ts
> +		const itemsSplitByNewline = key.toString().split('\n');
Chain instead of assign?

2023-05-19 08:21 UTC, fortunato commented on src/services/import-span-measure-options.ts
> +		return measureOption.measureItems.some((item) => {
Can be written as one-liner without curly braces

2023-05-19 08:21 UTC, fortunato commented on src/services/import-span-measure-options.ts
> +			const foundMeasureOption = this.jsonData.spanMeasureOptions.find((item) => {
Can be written as a one-liner without curly braces

2023-05-19 08:21 UTC, fortunato commented on src/services/import-span-measure-options.ts
> +			const item = {
Arguably a useless assignment

2023-05-19 08:21 UTC, fortunato commented on src/services/import-span-measure-options.ts
> +		const measureOptionsArray = Array.from(Object.values(measureOptions));
Useless assignment

2023-05-19 08:21 UTC, fortunato commented on src/services/import-span-measure-options.ts
> +		const fetchBestekposten = this.fetchBestekpostenFromSheet(
Useless assignments

2023-05-19 08:21 UTC, fortunato commented on src/services/import-span-measure-options.ts
> +		const maxRow = 9628;
Is it worth adding a comment on how this number is relevant?

2023-05-19 08:21 UTC, fortunato commented on src/services/import-span-measure-options.ts
> +
Why the newline here?

2023-05-19 08:21 UTC, fortunato commented on src/services/import-span-measure-options.spec.ts
> +
Why the newline here?

2023-05-19 08:21 UTC, fortunato commented on src/services/import-span-measure-options.spec.ts
> +import fs from 'fs';
Nice one :ok_hand:

2023-05-22 09:59 UTC, bennyvdhoogen commented on src/services/import-span-measure-options.ts
> +		const fetchMaterialen = this.fetchMaterialenFromSheet(file['M-nummers'], this.jsonData.spanMeasureItemOptions);
Agree with that one, renamed these to 'get...'

2023-05-22 10:05 UTC, bennyvdhoogen commented on src/services/import-span-measure-options.ts
> +import * as fs from 'fs';
I would be in favor if that is possible. Most frameworks I have worked with use a folder/namespace for CLI command such as this, but I think having stuff like this in a specific module aligns with the notion that we split our code based on a different domain. Will try to move this stuff to the `span-installation` folder -- although we had our thoughts about that one I guess? Perhaps better to do make a small refactor ticket for ths?

2023-05-22 10:34 UTC, fortunato approved these changes

2023-05-22 14:41 UTC, merged