Draft: feat: mjop export
Amsterdam/bmi-aip-graphql-service pull request #412
Opened 2023-06-14 09:27 UTC by anaim

2023-06-14 12:25 UTC, bennyvdhoogen commented on src/schema/mjop-export/mjop-measures.service.ts
> +						if (cyclicMeasure.cycle < 1) {
I see a couple of arbitrary numbers in this segment (<= 20, <= 120, <1) which I do not directly understand. Perhaps it would be better to come up with descriptive variable names for these numbers? Just like you do with yearNumber and currentYear.

2023-06-14 12:28 UTC, bennyvdhoogen commented on src/schema/mjop-export/mjop-report-survey/add-mjop-sheet.service.ts
> +		for (let i = 0; i <= 20; i++) {
Just like earlier, could you perhaps come up with a descriptive variable instead of 20? I guess it's the amount of years that are plotted in the exported file. Perhaps `amountOfYearsPlotted` or something along those lines could work?

2023-06-14 12:29 UTC, bennyvdhoogen reviewed
Looks good! Couple of minor comments.

2023-06-14 13:34 UTC, fortunato requested changes

2023-06-14 13:34 UTC, fortunato commented on src/schema/derived-condition-score/derived-condition-score.module.ts
> +import { Module } from '@nestjs/common';
Does this module deserve a place in the schema directory if it doesn't have any resolvers?

2023-06-14 13:34 UTC, fortunato commented on src/schema/derived-condition-score/models/derived-condition-score.model.ts
> +	derivedScore: string;
Should this not be a number?

2023-06-14 13:34 UTC, fortunato commented on src/schema/derived-condition-score/models/derived-condition-score.model.ts
> +	careScore: string;
Should this not be a number?

2023-06-14 13:34 UTC, fortunato commented on src/schema/mjop-export/mjop-data.service.ts
> +				const unitProps = {
unitProps is untyped

2023-06-14 13:34 UTC, fortunato commented on src/schema/mjop-export/mjop-data.service.ts
> +			const elementWithUnits = {
Useless assignment. Why not just push the object straight into the elementData array? That way we get of the untyped elementWithUnits as well.

2023-06-14 13:34 UTC, fortunato commented on src/schema/mjop-export/mjop-export.module.ts
> +export class MjopExportModule {}
Should be MJOPExportModule IMO

2023-06-14 13:34 UTC, fortunato commented on src/schema/mjop-export/mjop-measures.service.ts
> +		for (const measure of measures) {
Why not use an actual .map() or .reduce()?

2023-06-14 13:34 UTC, fortunato commented on src/schema/mjop-export/mjop-measures.service.ts
> +				measure.unitPrice *
Do you think it is worth creating a util for this?

2023-06-14 13:34 UTC, fortunato commented on src/schema/mjop-export/mjop-measures.service.ts
> +				cyclicMeasure.unitPrice *
Do you think it is worth creating a util for this?

2023-06-14 13:34 UTC, fortunato commented on src/schema/mjop-export/queries/mjop-export-by-survey-id.handler.ts
> +export class MjopExportBySurveyIdHandler implements IQueryHandler<MjopExportBySurveyIdQuery> {
MJOPExportBySurveyIdHandler

2023-06-14 13:34 UTC, fortunato commented on src/schema/mjop-export/queries/mjop-export-by-survey-id.handler.ts
> +			console.error(err);
Use the Logger service instead of console.error

2023-06-14 13:34 UTC, fortunato commented on src/schema/mjop-export/types/cyclic-measure.ts
> +	maintenanceDescription: string; //'Maatregel'
Please add a space after opening a comment `// ...`.
Quotes can be removed from the comments

2023-06-14 13:34 UTC, fortunato commented on src/schema/mjop-export/types/defect.ts
> +	defectName: string; //'Schadebeeld'
Please add a space after opening a comment `// ....`
Quotes can be removed from the comments

2023-06-14 13:34 UTC, fortunato commented on src/schema/mjop-export/types/derived-condition-score-element.ts
> +	elementCondition: string; //'Conditiescore Element'
Please add a space after opening a comment `// ....`
Quotes can be removed from the comments

2023-06-14 13:34 UTC, fortunato commented on src/schema/mjop-export/types/measure.ts
> +	maintenanceDescription: string; //'Maatregel'
Please add a space after opening a comment `// ....`
Quotes can be removed from the comments

2023-06-14 13:34 UTC, fortunato commented on src/schema/mjop-export/types/mjop-record.ts
> +	asset: IAsset;
Please add a space after opening a comment `// ....`
Quotes can be removed from the comments

2023-06-14 13:34 UTC, fortunato commented on src/schema/mjop-export/types/unit.ts
> +	elementId: string;
Please add a space after opening a comment `// ....`
Quotes can be removed from the comments

2023-06-14 13:34 UTC, fortunato commented on src/schema/mjop-export/utils/measure.ts
> +export function MeasureTypes(value) {
I think we can improve the naming of this. It seems like we're doing a type of mapping here. `MeasureTypes` nor `measure` give me an indication of that.

2023-06-15 07:35 UTC, anaim commented on src/schema/derived-condition-score/models/derived-condition-score.model.ts
> +	derivedCareScore: string;
Data type is varchar(1)

2023-06-15 07:40 UTC, anaim commented on src/schema/mjop-export/mjop-data.service.ts
> +export class MjopDataService {
I took Ark survey as an example, but I want to change it

2023-06-15 07:42 UTC, anaim commented on src/schema/mjop-export/types/mjop-record.ts
> +	asset: IAsset;
Done

2023-06-15 07:44 UTC, anaim commented on src/schema/mjop-export/types/survey.ts
> +	condition: string;
Done

2023-06-15 07:44 UTC, anaim commented on src/schema/mjop-export/types/unit.ts
> +	elementId: string;
Done

2023-06-15 11:03 UTC, fortunato commented on src/schema/derived-condition-score/models/derived-condition-score.model.ts
> +	derivedCareScore: string;
On the database level I presume. But does it make sense to represent this value with a string in the GraphQL model? The variable name implies to me that it concerns a numeric value. If it is a numeric value stored as a string I think the choice for varchar(1) is essentially wrong. I would opt for a numeric value in the GraphQL model instead in such case.

2023-06-15 11:04 UTC, fortunato commented on src/schema/mjop-export/mjop-data.service.ts
> +export class MjopDataService {
I think it should be `ARK` instead of `Ark` also :grin:

2023-06-15 11:14 UTC, fortunato commented on src/schema/derived-condition-score/models/derived-condition-score.model.ts
> +	derivedCareScore: string;
Aha, i see that actual string values are stored there as well. What do you think about introducing an enum for the possible values? The options are not exhaustive right?

2023-06-19 06:20 UTC, anaim commented on src/schema/mjop-export/types/mjop-record.ts
> +	// elements: IElement[];
Done

2023-06-19 06:20 UTC, anaim commented on src/schema/decomposition/element.service.ts
> +	// }
Done

2023-06-19 06:23 UTC, anaim commented on src/schema/mjop-export/types/survey.ts
> +export interface ISurvey {
Good Idea

2023-06-19 12:59 UTC, anaim commented on src/schema/mjop-export/mjop-measures.service.ts
> +						if (cyclicMeasure.cycle < 1) {
Donw

2023-06-19 13:16 UTC, anaim commented on src/schema/mjop-export/mjop-data.service.ts
> +export class MjopDataService {
Done

2023-06-19 13:23 UTC, anaim commented on src/schema/derived-condition-score/models/derived-condition-score.model.ts
> +	careScore: string;
changed

2023-06-19 13:23 UTC, anaim commented on src/schema/derived-condition-score/models/derived-condition-score.model.ts
> +	derivedScore: string;
changed

2023-06-21 07:54 UTC, anaim commented on src/schema/derived-condition-score/derived-condition-score.module.ts
> +import { Module } from '@nestjs/common';
Done

2023-06-22 12:03 UTC, anaim commented on src/schema/mjop-export/queries/mjop-export-by-survey-id.handler.ts
> +			console.error(err);
Done

2023-06-22 12:03 UTC, anaim commented on src/schema/mjop-export/mjop-measures.service.ts
> +				cyclicMeasure.unitPrice *
I think it's too small to do that

2023-06-26 06:36 UTC, anaim commented on src/schema/mjop-export/mjop-export.controller.ts
> +			console.error(error);
Done

2023-06-26 06:36 UTC, anaim commented on src/schema/mjop-export/mjop-export-column.ts
> +	renderCell: (cell: Cell, value: any, rowIdx: number, columnIdx: string) => void;
TS2322: Type 'unknown' is not assignable to type 'CellValue'.

2023-06-26 06:36 UTC, anaim commented on src/schema/mjop-export/mjop-export.controller.ts
> +export class MjopExportController {
done

2023-06-26 06:36 UTC, anaim commented on src/schema/mjop-export/mjop-data.service.ts
> +	private getAssetProps(asset: Asset): IAsset {
changed

2023-06-26 06:37 UTC, anaim commented on src/schema/mjop-export/mjop-measures.service.ts
> +					for (let j = 0; j <= 120 - i; j++) {
Done

2023-06-26 06:37 UTC, anaim commented on src/schema/mjop-export/queries/mjop-export-by-survey-id.handler.ts
> +export class MjopExportBySurveyIdHandler implements IQueryHandler<MjopExportBySurveyIdQuery> {
Done

2023-06-26 06:38 UTC, anaim commented on src/schema/mjop-export/types/cyclic-measure.ts
> +	maintenanceDescription: string; //'Maatregel'
Done

2023-06-26 06:38 UTC, anaim commented on src/schema/mjop-export/types/defect.ts
> +	defectName: string; //'Schadebeeld'
Done

2023-06-26 06:38 UTC, anaim commented on src/schema/mjop-export/types/derived-condition-score-element.ts
> +	elementCondition: string; //'Conditiescore Element'
Done

2023-06-26 06:38 UTC, anaim commented on src/schema/mjop-export/types/measure.ts
> +	maintenanceDescription: string; //'Maatregel'
Done

2023-06-26 07:59 UTC, fortunato approved these changes

2023-06-26 10:21 UTC, merged