Feature/baip 1444
Amsterdam/bmi-aip-graphql-service pull request #446
Opened 2023-07-26 13:14 UTC by anaim

2023-07-26 13:26 UTC, bennyvdhoogen commented
Code zit er goed uit qua logica Abdel! 

Wel vind ik `ovs-decomposition` een te generieke bewoording voor het model en de bijbehorende methods/acties voor wat je doet. Als ik het goed begrijp wil je steeds het techView ID invullen bij entiteiten, dan zou ik dat in het command/method willen teruglezen. Iets als `AddOVSDecompositionToTechviewID' -- of iets treffenders. Daarnaast zie ik nog een aantal andere props worden geüpdate. Zou je nog naar de naamgeving willen kijken? Ik zal een comment plaatsen per bestand.

2023-07-26 13:28 UTC, bennyvdhoogen requested changes

2023-07-26 13:28 UTC, bennyvdhoogen commented on src/schema/span-installation/__stubs__/junction-box.ts
> +	// techViewId: new Decimal(10),
Can be removed?

2023-07-26 13:28 UTC, bennyvdhoogen commented on src/schema/span-installation/models/ovs-decomposition.model.ts
> +export class OVSDecompositionModel {
Zou je een specifiekere naam willen bedenken hiervoor?

2023-07-26 13:28 UTC, bennyvdhoogen commented on src/schema/span-installation/ovs-decomposition.repository.ts
> +	async updateOVSDecomposition(input: UpdateOVSDecompositionInput): Promise<string> {
Zou je een specifiekere naam willen bedenken hiervoor?

2023-07-26 13:28 UTC, bennyvdhoogen commented on src/schema/span-installation/commands/update-ovs-decomposition.handler.ts
> +export class UpdateOVSDecompositionHandler implements ICommandHandler<UpdateOVSDecompositionCommand> {
Zou je een specifiekere naam willen bedenken hiervoor?

2023-07-27 07:25 UTC, anaim commented on src/schema/span-installation/__stubs__/junction-box.ts
> +	// techViewId: new Decimal(10),
Done

2023-07-27 07:25 UTC, anaim commented on src/schema/span-installation/models/ovs-decomposition.model.ts
> +export class OVSDecompositionModel {
Done

2023-07-27 07:25 UTC, anaim commented on src/schema/span-installation/commands/update-ovs-decomposition.handler.ts
> +export class UpdateOVSDecompositionHandler implements ICommandHandler<UpdateOVSDecompositionCommand> {
Done

2023-07-27 07:26 UTC, anaim commented on src/schema/span-installation/ovs-decomposition.repository.ts
> +	async updateOVSDecomposition(input: UpdateOVSDecompositionInput): Promise<string> {
Done

2023-07-27 12:28 UTC, bennyvdhoogen approved these changes

2023-08-01 12:44 UTC, merged