refactor: WIP changed design of the OVS export to be aligned with MJO…
Amsterdam/bmi-aip-graphql-service pull request #459
Opened 2023-08-11 09:35 UTC by bennyvdhoogen

…P export

2023-08-14 12:24 UTC, fortunato requested changes
Nearly there :+1:

2023-08-14 12:24 UTC, fortunato commented on src/api/span-installation-export/__stubs__/ovs-asset.ts
> +const ovsAssetBaseDataStub = {
Can these objects be typed?

2023-08-14 12:24 UTC, fortunato commented on src/api/span-installation-export/__stubs__/ovs-export-data.ts
> +const assetBaseData = {
Can these objects be typed?

2023-08-14 12:24 UTC, fortunato commented on src/api/span-installation-export/add-ovs-sheet.service.ts
> +		// actually redundant, but for the sake of clarity
The newline following the comment confuse ma about which code block it belongs to. 
May I request comments be starting with a capital letter?

2023-08-14 12:24 UTC, fortunato commented on src/api/span-installation-export/add-ovs-sheet.service.ts
> +		this.renderColumns(columns, rowData, newRow, startingCol); // Apply cell styles
How do you feel about keeping comments consistently in the same place across a code block?

2023-08-14 12:24 UTC, fortunato commented on src/api/span-installation-export/add-ovs-sheet.service.ts
> +		return new Promise((resolve) => {
This is a redundant promise construct. Considering the function is declared as async, it returns a promise regardless of the method of returning. Simply returning the array will do.

2023-08-14 12:24 UTC, fortunato commented on src/api/span-installation-export/add-ovs-sheet.service.ts
> +		return new Promise((resolve) => {
This is a redundant promise construct. Considering the function is declared as async, it returns a promise regardless of the method of returning. Simply returning the array will do.

2023-08-14 12:24 UTC, fortunato commented on src/api/span-installation-export/add-ovs-sheet.service.ts
> +		return new Promise((resolve) => {
This is a redundant promise construct. Considering the function is declared as async, it returns a promise regardless of the method of returning. Simply returning the array will do.

2023-08-14 12:24 UTC, fortunato commented on src/api/span-installation-export/span-installation-export.repository.ts
> +		const output = spanInstallations.map((spanInstallation) => {
Useless assignment

2023-08-14 12:24 UTC, fortunato commented on src/api/span-installation-export/span-installation-export.service.ts
> +		const spanInstallations = await this.spanRepository.findByObject(objectId);
I'd be happy if you'd change this to the map and return statement (optional)

2023-08-14 12:24 UTC, fortunato commented on src/api/span-installation-export/span-installation-export.service.ts
> +		return spanInstallations.map((spanInstallation: OVSExportSpanInstallationWithBatchDetails) => {
Did you consider writing this without return statement? (saves a few lines :man_shrugging: )

2023-08-14 12:24 UTC, fortunato commented on src/api/span-installation-export/span-installation-export.service.ts
> +		return spanInstallations.map((spanInstallation: OVSExportSpanInstallationWithBatchDetails) => {
Did you consider writing this without return statement? (saves a few lines :man_shrugging: )

2023-08-14 12:24 UTC, fortunato commented on src/api/span-installation-export/span-installation-export.repository.ts
> +		const output = spanInstallations.map((spanInstallation) => {
Did you consider writing this without return statement? (saves a few lines :man_shrugging: )

2023-08-14 12:24 UTC, fortunato commented on src/schema/batch/batch.repository.ts
> +		const batches = await this.prisma.batches.findMany({
Useless assignment

2023-08-14 12:58 UTC, bennyvdhoogen commented on src/api/span-installation-export/span-installation-export.repository.ts
> +		const output = spanInstallations.map((spanInstallation) => {
Yes, as per the feedback in the other PR. Should be updated now!

2023-08-14 12:59 UTC, bennyvdhoogen commented on src/api/span-installation-export/add-ovs-sheet.service.ts
> +		this.renderColumns(columns, rowData, newRow, startingCol); // Apply cell styles
Good point. Updated!

2023-08-14 13:15 UTC, bennyvdhoogen commented on src/api/span-installation-export/span-installation-export.service.ts
> +		return spanInstallations.map((spanInstallation: OVSExportSpanInstallationWithBatchDetails) => {
Updated!

2023-08-14 13:23 UTC, bennyvdhoogen commented on src/api/span-installation-export/add-ovs-sheet.service.ts
> +		return new Promise((resolve) => {
Ah, this was bound to happen I guess :) This construction/pattern is inherited directly from `add-mjop-sheet.service.ts` where the same feedback would apply then. 

I've ran the three `get...Columns` methods through GPT to simplify them. It changed 3 things:

- Removed the unnecessary wrapping of new Promise((resolve) => {...}) since Promise.resolve() achieves the same result.
- Directly returned the array of OVSExportColumn objects instead of creating a variable columns and then resolving it. This simplifies the structure.
- Removed the intermediate resolve call and returned the array directly within the Promise.resolve() function. This reduces unnecessary nesting.

2023-08-15 06:31 UTC, fortunato commented on src/api/span-installation-export/span-installation-export.repository.ts
> +		const output = spanInstallations.map((spanInstallation) => {
I meant it could be written like so:
```typescript
return spanInstallations.map((spanInstallation) => ({
    ...spanInstallation,
    attributes: spanInstallation.attributes as unknown as IPassport,
}));
```

2023-08-15 06:56 UTC, fortunato commented on src/api/span-installation-export/span-installation-export.service.ts
>  		const result = [];
This would benefit from a type as part of the assignment IMHO. It is inferred as `any[]` atm.

2023-08-15 08:04 UTC, fortunato approved these changes

2023-08-15 12:09 UTC, merged