feat: CRUD operations JuctionBox, Supportsystem and Luminaire
Amsterdam/bmi-aip-graphql-service pull request #67
Opened 2022-08-19 09:10 UTC by anaim

2022-08-19 09:36 UTC, svbeusekom commented on src/schema/span-installation/luminaire.resolver.ts
> +		return LuminaireFactory.CreateLuminaire(domainLuminaire);
I believe this should be `UpdateLuminaire` instead of `CreateLuminaire`

2022-08-19 09:36 UTC, svbeusekom commented on src/schema/span-installation/luminaire.resolver.ts
> +		return LuminaireFactory.CreateLuminaire(domainLuminaire);
I believe this should be `DeleteLuminaire` instead of `CreateLuminaire`

2022-08-19 09:36 UTC, svbeusekom commented on src/schema/span-installation/luminaire.resolver.ts
> +		return this.luminaireService.getLuminaires(supportSystemId);
I don't fully understand the relation between the support system and surveys, but is it correct that the `supportSystemId` is used to retrieve survey luminaires?

2022-08-19 09:38 UTC, svbeusekom commented on src/schema/span-installation/luminaire.resolver.ts
> +		return LuminaireFactory.CreateLuminaire(domainLuminaire);
Never mind, just noticed this is a factory, not a service.

2022-08-19 09:38 UTC, svbeusekom commented on src/schema/span-installation/luminaire.resolver.ts
> +		return LuminaireFactory.CreateLuminaire(domainLuminaire);
Never mind, just noticed this is a factory, not a service.

2022-08-19 10:20 UTC, anaim commented on src/schema/span-installation/luminaire.resolver.ts
> +		return this.luminaireService.getLuminaires(supportSystemId);
This is the Fortunato comment for surveyId in support system model: "// 1 survey per contract; decomposition is scoped by survey/contract"

2022-08-19 11:09 UTC, svbeusekom commented on src/schema/span-installation/luminaire.resolver.ts
> +		return this.luminaireService.getLuminaires(supportSystemId);
Alright, clear. Thanks!

2022-08-22 08:19 UTC, fortunato requested changes
Looks neat :+1:

2022-08-22 09:34 UTC, fortunato requested changes

2022-08-22 09:34 UTC, fortunato commented on src/schema/span-installation/support-system.resolver.ts
> +import { Args, Mutation, Query, Resolver } from '@nestjs/graphql';
I am missing a field resolver which allows for retrieving the Luminaire children in case of a support system of type "tension-wire"

2022-08-22 11:28 UTC, anaim commented on src/schema/span-installation/support-system.resolver.ts
> +import { Args, Mutation, Query, Resolver } from '@nestjs/graphql';
Done

2022-08-22 11:28 UTC, anaim commented on src/schema/span-installation/support-system.factory.ts
> +		supportSystem.type = getSupportSystemType(type);
Done

2022-08-22 11:28 UTC, anaim commented on src/schema/span-installation/support-system.repository.ts
> +	async deleteSupportSystem(identifier: string): Promise<SupportSystem> {
Done

2022-08-22 11:28 UTC, anaim commented on src/types/spanInstallation/support-system.ts
> +export function getSupportSystemTypeDetailed(supportSystemTypeDetailed: string): SupportSystemTypeDetailed {
Done

2022-08-22 11:29 UTC, anaim commented on src/types/spanInstallation/support-system.ts
> +export function getSupportSystemType(supportSystemType: string): SupportSystemType {
Done

2022-08-22 11:29 UTC, anaim commented on src/types/spanInstallation/span-luminaire.ts
> +
Done

2022-08-22 11:29 UTC, anaim commented on src/schema/span-installation/__stubs__/luminaire.ts
> +	supplierType: 'two',
Done

2022-08-22 11:29 UTC, anaim commented on src/schema/span-installation/__stubs__/luminaire.ts
> +	lightSupplierType: 'two',
Done

2022-08-22 11:29 UTC, anaim commented on src/schema/span-installation/__stubs__/support-system.ts
> +	type: 'facade',
Done

2022-08-22 13:13 UTC, svbeusekom commented on src/schema/span-installation/support-system.resolver.spec.ts
> +	// test('getSurveySupportSystems returns an array of support system objects', async () => {
It is changed, and done. I introduced a querybus and appropriate handler, as there is also a commandbus and handlers. I want to press on using query handlers AS WELL as command handlers, considering both these implementations are part of the CQRS principle. Only using one defeats the purpose.

2022-08-22 14:29 UTC, svbeusekom approved these changes

2022-08-22 20:42 UTC, svbeusekom commented
Can this be merged?

2022-08-23 08:11 UTC, merged