Bug/colon in folder name
Amsterdam/bmi-aip-graphql-service pull request #86
Opened 2022-08-30 15:18 UTC by reno1979

Windows can not handle certain characters inside a directory name, in this case the colon.

- renamed / changed directory structure

2022-12-28 15:05 UTC, fortunato requested changes

2022-12-28 15:05 UTC, fortunato commented on package.json
> +		"generate:gisib-api-types": "node_modules/.bin/ts-node scripts/generate/gisib-api-types/index.ts"
May I suggest we just rename the `generate:gisib-api-types` directory to `generate-gisib-api-types`. I can't currently make a reasonable assumption that we need a "generate namespace".

2023-01-11 10:06 UTC, bennyvdhoogen commented on package.json
> +		"generate:gisib-api-types": "node_modules/.bin/ts-node scripts/generate/gisib-api-types/index.ts"
Agree with this, @anaim does too.

2023-01-11 10:38 UTC, anaim approved these changes

2023-01-11 10:43 UTC, merged

2023-01-11 10:43 UTC, anaim approved these changes